name: app_flutter

version: 0.0.1

publish_to: none

description: app de aprendizagem da estrutura do flutter com um pouco de Getx 

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.6.5
  intl: ^0.18.0
  material_dialogs: ^1.1.3
  transparent_image: ^2.0.0
  logger: ^1.1.0
  dog: ^1.4.0
  dio: ^5.1.1
  url_launcher: ^6.1.8
  package_info_plus: ^3.0.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/
