// Mocks generated by Mockito 5.4.0 from annotations
// in app_flutter/test/modules/example/domain/usecases/get_users_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app_flutter/modules/home/infra/datasources/get_users_datasource.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetUsersDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUsersDataSource extends _i1.Mock implements _i2.GetUsersDataSource {
  @override
  _i3.Future<List<Map<String, dynamic>>> getUsers() => (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(<Map<String, dynamic>>[]),
        returnValueForMissingStub: _i3.Future<List<Map<String, dynamic>>>.value(<Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);
}
